# Generated by Django 5.1 on 2024-08-16 23:56

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Título')),
                ('pub_date', models.DateField(default=datetime.date.today)),
                ('content', models.TextField(verbose_name='Contenido')),
            ],
            options={
                'db_table': 'Article',
                'ordering': ['pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Categoría')),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='article', to='blog.article')),
            ],
            options={
                'db_table': 'Category',
                'ordering': ['name'],
            },
        ),
    ]
