# Generated by Django 5.1 on 2024-08-22 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='article_id',
        ),
        migrations.AddField(
            model_name='article',
            name='article_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='article', to='blog.article'),
            preserve_default=False,
        ),
    ]
