# Generated by Django 5.1 on 2024-08-24 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_category_options_alter_article_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='article', to='blog.category', verbose_name='Categoría'),
        ),
    ]
