# Generated by Django 5.1 on 2024-08-28 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_article_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='static/img/default.jpg', upload_to='static/img/', verbose_name='Imagen'),
        ),
    ]
