# Generated by Django 5.1 on 2024-08-28 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='media/img/default.jpg', upload_to='media/img/', verbose_name='Imagen'),
        ),
    ]
