# Generated by Django 5.1 on 2024-08-28 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='imagen/default.jpg', upload_to='imagen/', verbose_name='Imagen'),
        ),
    ]
